title: "Abdelrahman Diknash Portfolio"
tagline: "Labs • Writeups • Projects • Certifications"
description: "Cybersecurity analyst specializing in threat detection, incident response, and blue team operations."
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/style.scss"

