title: "Abdelrahman's Cybersecurity Portfolio"
tagline: "Labs • Writeups • Projects • Certifications"
description: "Cybersecurity analyst focused on detection, blue team, and threat hunting."
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/style.scss"

